hub:
  image: selenium/hub
  ports:
    - 4444:4444
firefox:
  image: selenium/node-firefox
  links:
    - hub:hub
  ports:
    - 5555:5555
chrome:
  image: selenium/node-chrome
  links:
    - hub:hub
  ports:
    - 5556:5556